In [2]:
import numpy as np
a=np.arange(4)
a

array([0, 1, 2, 3])

In [3]:
b=a
c=a
d=b
a[0]=0.3
a

array([0, 1, 2, 3])

In [3]:
a[0]=11
a

array([11,  1,  2,  3])

In [4]:
b is a

True

In [5]:
b

array([11,  1,  2,  3])

In [6]:
c

array([11,  1,  2,  3])

In [7]:
d is a

True

In [8]:
d[1:3]=[22,33]
d

array([11, 22, 33,  3])

In [9]:
a

array([11, 22, 33,  3])

In [10]:
b

array([11, 22, 33,  3])

In [11]:
c

array([11, 22, 33,  3])

In [12]:
b=a.copy() #deep copy
b

array([11, 22, 33,  3])

In [13]:
a[3]=44
a

array([11, 22, 33, 44])

In [14]:
b

array([11, 22, 33,  3])