基礎運算1

In [2]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)

print(a,b)
c=a+b
print(c)

[10 20 30 40] [0 1 2 3]
[10 21 32 43]


In [5]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)

c=10*np.cos(a)
print(c)

[-8.39071529  4.08082062  1.5425145  -6.66938062]


In [8]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)

print(b)
print(b<3)

[0 1 2 3]
[ True  True  True False]


In [9]:
import numpy as np
a = np.array([[1,1],
              [0,1]])
b = np.arange(4).reshape((2,2))

print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [12]:
import numpy as np
a = np.array([[1,1],
              [0,1]])
b = np.arange(4).reshape((2,2))

c=a*b
c_dot = np.dot(a,b)
c_dot_2=a.dot(b)


print(c_dot)
print(c_dot_2)

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]


In [4]:
a=np.random.random((2,4))

print(a)
print(np.sum(a,axis=1)) #axis=1 在列中求和
print(np.min(a,axis=0)) #axis=0 在行中求 最小值
print(np.max(a,axis=1)) #axis=1 在列中求 最大值


[[0.27846998 0.28969627 0.61505342 0.02088917]
 [0.94420307 0.69083327 0.10816598 0.67911991]]
[1.20410883 2.42232223]
[0.27846998 0.28969627 0.10816598 0.02088917]
[0.61505342 0.94420307]


基礎運算2

In [2]:
import numpy as np

A=np.arange(2,14).reshape((3,4))

print(A)
print(np.argmin(A)) #最小索引
print(np.argmax(A)) #最大索引

print(np.mean(A))  #平均
print(A.mean())
print(np.average(A))

print(np.median(A)) #中位數
print(np.cumsum(A)) #累加
print(np.diff(A))   #累差

print(np.nonzero(A)) #非0 值的位置

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [36]:
A=np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.sort(A)) #有排序的

print(np.transpose(A)) #反矩正
print((A.T).dot(A))


[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


In [38]:
A=np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.clip(A,5,9)) #<5皆=5 >9皆=9

print(np.mean(A,axis=0)) #axis 可對行列進行平均數計算

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
[10.  9.  8.  7.]
