In [10]:
import numpy as np

A = np.arange(3,15).reshape((3,4))
print(A)
print(A[2][1])
print(A[2,1])
print(A[2,0:3])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
12
12
[11 12 13]


In [12]:
A = np.arange(3,15).reshape((3,4))
print(A)

for column in A.T:
   print(column)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [14]:
A = np.arange(3,15).reshape((3,4))
print(A)
print(A.flatten())
for item in A.flat:
   print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
