In [1]:
import numpy as np

A =np.array([1,1,1])
B =np.array([2,2,2])

C = np.vstack((A,B)) #vertical stack   上下合併
D=np.hstack((A,B))   #horizontal stack 左右合併
print(C)
print(D)
print(A.shape,C.shape,D.shape)
print(A.reshape(3,1))
print(A[:,np.newaxis])

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3,) (2, 3) (6,)
[[1]
 [1]
 [1]]
[[1]
 [1]
 [1]]


In [3]:
A =np.array([1,1,1])[:,np.newaxis]
B =np.array([2,2,2])[:,np.newaxis]

C = np.vstack((A,B)) #vertical stack   上下合併
D=np.hstack((A,B))   #horizontal stack 左右合併
print(A)
print(C)
print(D)
print(A.shape,D.shape)



[[1]
 [1]
 [1]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


In [4]:
A =np.array([1,1,1])[:,np.newaxis]
B =np.array([2,2,2])[:,np.newaxis]

C = np.concatenate((A,B,B,A),axis=0) #concatenate 可進行多個矩正的合併
E = np.concatenate((A,B,B,A),axis=1)
print(C)
print(E)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


Numpy array 分割

In [20]:
A = np.arange(12).reshape((3,4))
print(A)

print(np.split(A,3,axis=0)) #預設為axis=0

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [6]:
A = np.arange(12).reshape((3,4))
print(A)

print(np.array_split(A,3,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [24]:
A = np.arange(12).reshape((3,4))
print(A)

print(np.vsplit(A,3))
print(np.hsplit(A,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
