Numpy 属性 #3

In [4]:
import numpy as np

array = np.array([[1,2,3],
                 [2,3,4]])

print(array)
print('number of dim:',array.ndim)
print('shape:',array.shape)
print('size:',array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


numpy的創建array #4

In [10]:
a = np.array([2,23,4],dtype=np.int)
print(a.dtype)
#int 後面可用16 32 64

int32


In [11]:
a = np.array([2,23,4],dtype=np.float)
print(a.dtype)
#int 後面可用16 32 64

float64


In [12]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a=np.ones((3,4),dtype=np.int16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [15]:
a = np.empty((3,4))
print(a)
#接近於0

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [17]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
a = np.linspace(1,10,6).reshape((2,3))
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
